/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;


public class App {
  public static void main(String[] args) {
    Graph<String> graph = new Graph<>();
    Vertex<String> a = graph.addVertex("A");
    Vertex<String> b = graph.addVertex("B");
    Vertex<String> c = graph.addVertex("C");
    Vertex<String> d = graph.addVertex("D");
    Vertex<String> e = graph.addVertex("E");



    graph.addEdge(a, b,5);
    graph.addEdge(a, c);
    graph.addEdge(b, d);
    graph.addEdge(c, d);
    graph.addEdge(d, e);

//    System.out.println(a.getEdges());
//    System.out.println(graph.getNeighbors(a));
//    System.out.println(b.getEdges());
//    System.out.println(graph.getNeighbors(b));
//    System.out.println(c.getEdges());
//    System.out.println(graph.getNeighbors(c));
//    System.out.println(d.getEdges());
//    System.out.println(graph.getNeighbors(d));
//    System.out.println(e.getEdges());
//    System.out.println(graph.getNeighbors(e));


//    System.out.println(a.getEdges());
    graph.print();
//    System.out.println(graph.getNeighbors(d));

  }
}
