/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTabels;

import org.junit.Test;

import java.util.Arrays;
import java.util.TreeSet;

import static org.junit.Assert.*;

public class AppTest {

  @Test
  public void repeatedWordTester() {
    String str = "Modify your function to return a count of each of the words in the provided string";
    assertEquals("There was an error in the method of repeated word", "of", App.repeatedWord(str));
    String str2 = "A wiki (/ˈwɪki/ (About this soundlisten) WIK-ee) is a hypertext publication collaboratively edited and managed by its own audience directly using a web browser. A typical wiki contains multiple pages for the subjects or scope of the project and could be either open to the public or limited to use within an organization for maintaining its internal knowledge base.";
    assertEquals("There was an error in the method of repeated word", "a", App.repeatedWord(str2));
  }

  @Test
  public void treeIntersectionTest () {
    TreeSet<String> treeSet1 = new TreeSet<>();
    treeSet1.add("a");
    treeSet1.add("b");
    treeSet1.add("c");
    treeSet1.add("d");
    TreeSet<String> treeSet2 = new TreeSet<>();
    treeSet2.add("a");
    treeSet2.add("w");
    treeSet2.add("r");
    treeSet2.add("d");
    assertEquals("There was an error in the method of tree intersection", "{d=d, a=a}", App.treeIntersection(treeSet1, treeSet2).toString());
  }

  @Test
  public void joinTest () {
    HashTable<String, String> hashTable1 = new HashTable<>();
    hashTable1.add("a", "aa");
    hashTable1.add("b", "bb");
    hashTable1.add("c", "cc");
    HashTable<String, String> hashTable2 = new HashTable<>();
    hashTable2.add("a", "qq");
    hashTable2.add("c", "ww");
    hashTable2.add("d", "ee");
    String[][] actual = new String[][] {{"a", "aa", "qq"}, {"c", "cc", "ww"}, {"b", "bb", null}};
    assertArrayEquals("There was an error inside join left method",actual, App.join(hashTable1, hashTable2,true));
     }
}
