/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


import java.util.Arrays;

public class App {

  public static void main(String[] args) {
    LinkedList<Integer> testing = new LinkedList<>();
    System.out.println("The head when initialize new linked List is:  =>  " + testing.head);
    System.out.println("Adding {1,2,3,0,5,6,9,8} to the linked list");
    int[] inserted = {1, 2, 3, 0, 5, 6, 9, 8};
    //adding the number to linked list
    for (int num : inserted) testing.insert(num);
    System.out.println("now let's print the string method");
    System.out.println(testing.toString());
    System.out.println("let's check if it include number 5");
    System.out.println(testing.includes(5));
    System.out.println("let's check if it include number 10");
    System.out.println(testing.includes(10));
  }
}
