/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selectionSort;

import java.util.Arrays;

public class App {
  public static void main(String[] args) {
    int[] ints = {5, 7, 2, 1, 3, 4, 6};
    System.out.println("Let's Try To Sort this Array =>>  [5,7,2,1,3,4,6]");
    selectionSort(ints);
    System.out.println("Sorted Array =>> " + Arrays.toString(ints));
    int[] ints2 = {20, 18, 12, 8, 5, -2};
    System.out.println("Let's Try To Sort this Array =>>  [20,18,12,8,5,-2]");
    selectionSort(ints2);
    System.out.println("Sorted Array =>> " + Arrays.toString(ints2));
  }

  public static void selectionSort(int[] array) {
    for (int i = 0; i < array.length; i++) {
      int min = i;
      for (int j = i + 1; j < array.length; j++) {
        if (array[j] < array[min]) {
          min = j;
        }
      }
      int temp = array[i];
      array[i] = array[min];
      array[min] = temp;
    }
  }
}
